version: '3.5'

services:
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./backend-matriculas/.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  webserver:
    container_name: 'webserver'
    image: httpd:latest
    restart: always
    working_dir: /frontend-matriculas/app
    ports:
      - 8080:80
    volumes:
      - ./frontend-matriculas/src/:/usr/local/apache2/htdocs
  financeiro:
    container_name: 'financeiro'
    image: node:16
    restart: always
    working_dir: /backend-matriculas/microservice-financeiro/app
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=mysql://root:123456789@mysql:3306/financeiro
    volumes:
      - ./backend-matriculas/microservice-financeiro/dist/:/backend-matriculas/microservice-financeiro/app/dist/
      - ./backend-matriculas/microservice-financeiro/package.json:/backend-matriculas/microservice-financeiro/app/package.json
      - ./backend-matriculas/microservice-financeiro/prisma:/backend-matriculas/microservice-financeiro/app/prisma
    command: bash -c "npm install --omit=dev --force && npx prisma migrate dev && npm run start"
    depends_on:
      - mysql
      - rabbitmq
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'financeiro'
      MYSQL_PASSWORD: '123456789'
      MYSQL_ROOT_PASSWORD: '123456789'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  marketing:
    container_name: 'marketing'
    image: node:16
    restart: always
    working_dir: /backend-matriculas/microservice-marketing/app
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongo:27017/marketing
    volumes:
      - ./backend-matriculas/microservice-marketing/dist/:/backend-matriculas/microservice-marketing/app/dist/
      - ./backend-matriculas/microservice-marketing/package.json:/backend-matriculas/microservice-marketing/app/package.json
    command: bash -c "npm install --omit=dev --force && npm run start"
    depends_on:
      - mongo
      - rabbitmq
  mongo:
    container_name: 'mongoDb'
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    ports:
      - 27017:27017
    volumes:
      - ./backend-matriculas/microservice-marketing/data:/data/db
  pagamento:
    container_name: 'pagamento'
    image: node:16
    restart: always
    working_dir: /backend-matriculas/microservice-pagamento/app
    ports:
      - 3333:3333
    volumes:
      - ./backend-matriculas/microservice-pagamento/dist/:/backend-matriculas/microservice-pagamento/app/dist/
      - ./backend-matriculas/microservice-pagamento/package.json:/backend-matriculas/microservice-pagamento/app/package.json
    command: bash -c "npm install --omit=dev -f && npm run start"
    depends_on:
      - rabbitmq
  academico:
    container_name: 'academico'
    image: node:16
    restart: always
    working_dir: /backend-matriculas/microservice-academico/app
    ports:
      - 3002:3002
    environment:
      - DATABASE_URL=mysql://root:123456789@mysql:3306/academico
    volumes:
      - ./backend-matriculas/microservice-academico/dist/:/backend-matriculas/microservice-academico/app/dist/
      - ./backend-matriculas/microservice-academico/package.json:/backend-matriculas/microservice-academico/app/package.json
      - ./backend-matriculas/microservice-academico/prisma:/backend-matriculas/microservice-academico/app/prisma
    command: bash -c "npm install --omit=dev --force && npx prisma migrate dev && npm run start"
    depends_on:
      - mysql
      - rabbitmq
volumes:
  my-db:
